server:
  port: 8100
spring:
  application:
    name: client1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    id: biz1
    prefer-ip-address: true
    ip-adress: 127.0.0.1
user:
  biz2servicepath: http://localhost:8101